export const BRING_TASKS = 'bring_tasks'
export const LOADING_TASKS  = 'loading_tasks'
export const ERROR_TASKS  = 'error_tasks'
export const CHANGEUSERID_TASK  = 'changeUserID_Task'
export const CHANGETITLE_TASK  = 'changeTitle_Task'